app/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.sitemaps.views import sitemap
from booster.sitemaps import PostSitemap


sitemaps = {
 'posts': PostSitemap,
}




urlpatterns = [
   
              
    path('', include(('booster.urls','booster'), namespace='booster')),
    path('admin/', admin.site.urls),
    path('accounts/',include('allauth.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap')
    

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

booster/urls.py
from django.urls import path
from . import views


urlpatterns = [
        path('', views.new),
        path('tag/<slug:tag_slug>/', views.new, name='new_by_tag'),
        path('<int:id>/<slug:slug>/', views.detail , name='detail'),
        path('search', views.post_search, name='post_search'),
        path('suscriber', views.suscriber),
        path('add',views.addcom),
        path('about',views.index),
        path('contact', views.contct),

        
         
]

booster/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager


 

class Post(models.Model):
        STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
        )
        CATE=(
                ('education', 'education'),
        )
        title = models.CharField(max_length=250)
        slug = models.SlugField(max_length=250,unique_for_date='publish')
        cate = models.CharField(max_length=100,        choices=CATE   )
                
        
        author = models.ForeignKey(User, on_delete=models.CASCADE,  related_name='blog_posts')
        body = models.TextField()
        image=models.ImageField( upload_to="image", height_field=None, width_field=None, max_length=None)
        publish = models.DateTimeField(default=timezone.now)
        created = models.DateTimeField(auto_now_add=True)
        updated = models.DateTimeField(auto_now=True)
        status = models.CharField(max_length=10,        choices=STATUS_CHOICES,        default='draft')
        tags = TaggableManager()
        def get_absolute_url(self):
                return reverse('booster:detail', args=[self.id ,self.slug])      
       
        class Meta:
                ordering = ('-publish',)
                def __str__(self):
                        return self.title

       
  


class Blogdes(models.Model):        
        post=models.ForeignKey(Post,  on_delete=models.CASCADE)
        sub_title=models.CharField( max_length=250)
        description=models.TextField()
        image= models.ImageField( upload_to="image", height_field=None, width_field=None, max_length=None)


class  comment(models.Model):        
        postid=models.IntegerField()       
        body=models.CharField(max_length=250)
        name=models.CharField( max_length=150)
        email=models.EmailField( max_length=254)
        Date=models.DateTimeField( auto_now=True, auto_now_add=False)
        created = models.DateTimeField(auto_now_add=True)
        updated = models.DateTimeField(auto_now=True)
        def __str__(self):
            return self.body
 


class suscriberr(models.Model):
        email=models.EmailField( max_length=254)
        name=models.CharField( max_length=150)

class contact(models.Model):
    name=models.CharField( max_length=50)
    company=models.CharField( max_length=50)
    email=models.EmailField( max_length=254)
    message=models.TextField()
   
    def __str__(self):
        return self.name

    
    

booster/forms.py
from django import forms
from booster.models import comment,contact

                
    
class SearchForm(forms.Form):
        query = forms.CharField()


class contactForm(forms.ModelForm):
        class Meta:
                model = contact
                fields = ('name', 'email', 'company','message')

booster/views.py
from django.shortcuts import render,redirect, get_object_or_404
from booster.models import comment,Post,Blogdes,suscriberr,contact
from .forms import SearchForm,contactForm
from django.http import HttpResponseRedirect
from django.contrib import messages
from booster.templatetags import extras
import datetime
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from taggit.models import Tag
from django.db.models import Count
from booster.templatetags import extras

from django.contrib.postgres.search import SearchVector, SearchQuery,SearchRank






def contct(request):  
        form=contactForm()             
        if request.method=="POST":
                form = contactForm(request.POST)
                if form.is_valid():
                        form.save()                
                        return render(request,'thanks.html')               
                
        else:
                              
                return render(request,'contact.html', {'form':form})  






def suscriber(request):        
        if request.method=="POST":
                email=request.POST.get('emaiil')
                name=request.POST.get('namei')
                oko=suscriberr(email=email, name=name)
                oko.save()                
                return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/')) 
        else:
                return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/')) 



       
def post_search(request):
        form = SearchForm()
        query = None
        results = []
        if 'query' in request.GET:
                form = SearchForm(request.GET)
                if form.is_valid():
                        query = form.cleaned_data['query']
                        search_vector = SearchVector('title', weight='A') +  SearchVector('body', weight='B')
                        
                        search_query = SearchQuery(query)
                        results = Post.objects.annotate(search=search_vector, rank=SearchRank(search_vector, search_query) ).filter(rank__gte=0.3).order_by('-rank')
                        
        return render(request,'search.html', {'form': form, 'query': query, 'results': results})
        
         
 
def new(request, tag_slug=None):
        ptr1=Post.objects.all()
        form = SearchForm()
        tag = None
        if tag_slug:
                tag = get_object_or_404(Tag, slug=tag_slug)
                ptr1 = Post.objects.filter(tags__in=[tag])

        paginator = Paginator(ptr1, 1) # 3 posts in each page
        page = request.GET.get('page')
        try:
                posts = paginator.page(page)
        except PageNotAnInteger:
                posts = paginator.page(1)

        except EmptyPage:
                posts = paginator.page(paginator.num_pages)
        return render(request,'home.html' , {'fact': posts, 'form':form ,'page': page,'tag': tag})


     



def detail(request,id,slug):
        form = SearchForm()
        product = get_object_or_404(Post, id=id, slug=slug)
        rec=Post.objects.all()[0:4]
        part = Blogdes.objects.filter(post=id)       
        post_tags_ids = Post.tags.values_list('id', flat=True)
        similar_posts = Post.objects.filter(tags__in=post_tags_ids).exclude(id=id)
        similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags','-publish')[:4]
        com=comment.objects.filter(postid=id)
        count=comment.objects.filter(postid=id).count()
        return render(request,'detail.html', {'post': product, 'part':part ,'similar_posts': similar_posts ,'rec':rec ,'form':form ,'count':count, 'comment':com })
  
        


def index(request):
        return render(request,'about.html')



      















def addcom(request):                
        
        if request.method =='POST':                         
                body=request.POST.get('body')#comment
                ook=request.POST.get('id')
                name=request.POST.get('name')
                email=request.POST.get('email')               
                commentk=comment(postid=ook, name=name, email=email , body=body)
                if commentk is not None:
                        commentk.save()                
                        return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))
        else:
                return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))
                
                

        
 

booster/templates/about.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="Responsive Bootstrap 4 Magazine/Blog Theme">
	<meta name="author" content="Bootlab">

  <title>Milo - Magazine/Blog Theme</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


  
</head>
<body>   <header>
        <nav class="navbar navbar-expand-md navbar-light bg-white absolute-top">
          <div class="container">
    
            <button class="navbar-toggler order-2 order-md-1" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbar-left navbar-right" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
    
            <div class="collapse navbar-collapse order-3 order-md-2" id="navbar-left">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item dropdown">
                  <a class="nav-link " href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Home</a>
                 
                </li>
                
                
              </ul>
            </div>
    
            <a class="navbar-brand mx-auto order-1 order-md-3" href="/">Knowledge Booster</a>
    
            <div class="collapse navbar-collapse order-4 order-md-4" id="navbar-right">
              <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                  <a class="nav-link" href="/about">About</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="/contact">Contact</a>
                </li>
              </ul>
            </ul>
            
                                 <form class="form-inline" action="/search" >
                                  <input class="search js-search form-control form-control-rounded mr-sm-2" type="text"  required id="id_query" name="query" title="Enter search query here.." placeholder="Search.." aria-label="Search">
                                </form>
             
            </div>
          </div>
        </nav>
      </header>

      {% if messages %}
      {% for message in messages %}
      <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <strong>{{message}}</strong>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      {% endfor %}
      {% endif %} 
      <main class="main pt-4">

        <div class="container">
          <div class="row">
            <div class="col-md-8 mx-auto">
    
              <article class="card mb-4">
                <header class="card-header text-center">
                  <h1 class="card-title">Who are we?</h1>
                </header>
                <div class="card-body">
    
                  <p><strong>Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus.</strong></p>
    
                  <p>Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim.</p>
    
                  <img src="img/18.jpg" class="img-fluid mb-3" alt="Our team" />
    
                  <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem.</p>
    
                  <blockquote>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
                  </blockquote>
    
                  <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem.</p>
    
                  <div class="row">
                    <div class="col-md-4">
                      <ul>
                        <li>Donec quam felis</li>
                        <li>Consectetuer adipiscing</li>
                      </ul>
                    </div>
                    <div class="col-md-4">
                      <ul>
                        <li>Donec quam felis</li>
                        <li>Consectetuer adipiscing</li>
                      </ul>
                    </div>
                    <div class="col-md-4">
                      <ul>
                        <li>Donec quam felis</li>
                        <li>Consectetuer adipiscing</li>
                      </ul>
                    </div>
                  </div>
    
                  <p>Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus.</p>
    
                </div>
              </article><!-- /.card -->
    
            </div>
          </div>
        </div>
    
      </main>

      

  <div class="site-newsletter">
    <div class="container">
      <hr>
      
      <div class="text-center">
        <h3 class="h4 mb-2">Subscribe to our newsletter</h3>
        <p class="text-muted">Join our monthly newsletter and never miss out on new stories and promotions.</p>

        <div class="row">
          <div class="col-xs-12 col-sm-9 col-md-7 col-lg-5 ml-auto mr-auto">
                <form action="/suscriber" method="POST">
                        {% csrf_token%}

            <div class="input-group mb-3 mt-3">
              <input type="text" class="form-control" name="emaiil" placeholder="Email address" aria-label="Email address">
              <input type="hidden" class="form-control" placeholder="Email address" name="namei" value="contact" aria-label="Email address">
             
              <span class="input-group-btn">
                <button type="submit" class="btn btn-secondary">Subscribe</button>
        </form>
               
              </span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

 


    <div class="colo">
  <div class="container">
    <hr>
    <div class="row no-gutters">
      <div class="col-sm-6">
        <div class="row no-gutters">
          <div class="col-3">
            <a class="photo" href="#">
              <img 100px src="{% static 'images/b1.png' %}" alt="" height="100px" width="100%" />
            </a>
          </div>
          <div class="col-3">
            <a class="photo" href="#">
              <img 100px src="{% static 'images/b2.jpg' %}" alt="" height="100px"  width="100%" />
            </a>
          </div>
          <div class="col-3">
            <a class="photo" href="#">
              <img 100px src="{% static 'images/b3.jpeg' %}" alt="" height="100px" width="100%"  />
            </a>
          </div>
          <div class="col-3">
            <a class="photo" href="#">
              <img 100px src="{% static 'images/b4.jpeg' %}" alt="" height="100px" width="100%"  />
            </a>
          </div>
        </div>
      </div>
      <div class="col-sm-6">
        <div class="row no-gutters">
          <div class="col-3">
            <a class="photo" href="#">
              <img 100px src="{% static 'images/b5.jpeg' %}" alt=""height="100px" width="100%"  />
            </a>
          </div>
          <div class="col-3">
            <a class="photo" href="#">
              <img 100px src="{% static 'images/b6.jpeg' %}" alt="" height="100px" width="100%"  />
            </a>
          </div>
          <div class="col-3">
            <a class="photo" href="#">
              <img 100px src="{% static 'images/b7.jpeg' %}" alt="" height="100px" width="100%" />
            </a>
          </div>
          <div class="col-3">
            <a class="photo" href="#">
              <img 100px src="{% static 'images/b8.jpeg' %}" alt="" height="100px" width="100%" />
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</div>

  <footer class="site-footer bg-darkest">
    <div class="container">

      <ul class="nav justify-content-center">
        <li class="nav-item">
          <a class="nav-link" href="#">Privacy policy</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Terms</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/contact">Feedback</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/advertise">Advertise</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/contact">Contact</a>
        </li>
      </ul>
      <div class="copy">
        &copy; Knowledge booster 2019<br />
        All rights reserved
      </div>
    </div>
  </footer>


  
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  
</body>
</html>

booster/templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
  

  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <title>Hello, world!</title>

   {% block style%}
   {% endblock %}
   <style>
    .v{
      border-right: 1px solid black;
      height: 500px;
    }
    p{
        
      font-family: none;
  font-size: inherit;
  color: black;
  font-weight: 500;
}
    

h1{
color: darkgreen;
font-size: x-large;
font-family: revert;
}
   
.input-container {
display: -ms-flexbox; /* IE10 */
display: flex;
width: 100%;
margin-bottom: 15px;
}

.icon {
padding: 10px;
background: dodgerblue;
color: white;
min-width: 50px;
text-align: center;
}
.okk{
transform: translateX(+70%);
}
.input-field {
width: 100%;
padding: 10px;
outline: auto;
}

.input-field:focus {
border: 2px solid green;
}

/* Set a style for the submit button */
.btn1 {
background-color: crimson;
color: white;
padding: 15px 20px;
border: none;
cursor: pointer;
width: 100%;
opacity: 0.9;
}

.btn1:hover {
opacity: 1;
}

.item{
align-items: right;
}
.card{
width: 103%;

}
.btn{
color: blue;
}
span{
color:crimson
}
.o{
color: blueviolet;
}
.fa {
padding: 10px;
font-size: 30px;
min-width: 50px;
text-align: center;
text-decoration: none;


color: white;
}
.kalu11{
background-color: black;
}
.fa-facebook {
background: #3B5998;
color: white;
border-radius: 10px;
}

.fa-twitter {
background: #55ACEE;
color: white;
border-radius: 20px;
}
.fa-linkedin {
background: #007bb5;
color: white;
border-radius: 20px;
}
.fa-instagram {
background: crimson;
color: white;
border-radius: 20px;
}
.okay{
padding: 10px;
font-size: 30px;
min-width: 50px;
text-align: center;
text-decoration: none;
border-radius: 20px solid black;
color: crimson;



}

.fa:hover {
  opacity: 0.7;
}
.hide{
display: none;
}
p{
font-family:auto;
  font-size: larger;
}

.km{
font-family: auto;
color: aliceblue;
font-size: xx-large;
margin: 10px;
margin: 10px;
    padding: 5px;
    text-align: center;


}
.bg1{
background-color: black;
}
.kl{
  color: aqua;
  transform: translate( -50px ,-15px);
  text-align: center;


}
.kal{
color: black ;
background-color: transparent;
font-size: small;

}
.post-f-t{
transform: translateY(-50px);
}
.mh{
background-color: black;
height: 100px;

}


   </style>
  </head>
  <body>
    {% load humanize %} 
    {% load extras %}
    <header>
      <nav class="navbar navbar-expand-md navbar-light bg-white absolute-top">
        <div class="container">
  
          <button class="navbar-toggler order-2 order-md-1" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbar-left navbar-right" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
  
          <div class="collapse navbar-collapse order-3 order-md-2" id="navbar-left">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item dropdown">
                <a class="nav-link " href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Home</a>
               
              </li>
              
              
            </ul>
          </div>
  
          <a class="navbar-brand mx-auto order-1 order-md-3" href="/">Knowledge Booster</a>
  
          <div class="collapse navbar-collapse order-4 order-md-4" id="navbar-right">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                <a class="nav-link" href="/about">About</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/contact">Contact</a>
              </li>
            </ul>
          </ul>
          
                               <form class="form-inline" action="/search" >
                                <input class="search js-search form-control form-control-rounded mr-sm-2" type="text"  required id="id_query" name="query" title="Enter search query here.." placeholder="Search.." aria-label="Search">
                              </form>
           
          </div>
        </div>
      </nav>
    </header>

          {% if messages %}
          {% for message in messages %}
          <div class="alert alert-warning alert-dismissible fade show" role="alert">
            <strong>{{message}}</strong>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          {% endfor %}
          {% endif %} 

          <hr>



<!---------------------------main content sec-1---------------------------->







    <div class="container">  
         <div class="row">
               
                <div class="col-lg-7">
                  <!--main 1st part-->
                  
                    
                      <!-- Breadcrumbs -->
                     
                       {% block strip %}
                       {% endblock %}
                     
                      
                    
                  
                  {% block main%}

                          {% endblock%}
                </div>
                <!--main 2nd part-->
                <div class="col-lg-4">

                  


  

  <aside class="sidebar sidebar-sticky">
    
    
    <!-- /.card -->
    {% block popular %}
    {% endblock %}
    
   
    {% block recentpost %}
    {% endblock %}


    




  </aside>
  <aside class="sidebar">
    


    <div class="card mb-4">
      <div class="card-body">
        <h4 class="card-title">About</h4>
        <p class="card-text">Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam <a href="#">semper libero</a>, sit amet adipiscing sem neque sed ipsum. </p>
      </div>
    </div><!-- /.card -->
  </aside>

  {% block signup%}
    {% endblock%}



                 


















                  
                        
                        
                        
                        
                       

                       
                            

                </div><!--main2-->
       </div><!--row-->

              
    </div><!--container-->


   

  <div class="container">
    <hr>
    <div class="row no-gutters">
      <div class="col-sm-6">
        <div class="row no-gutters">
          <div class="col-3">
            <a class="photo" href="#">
              <img 100px src="{% static 'images/b1.png' %}" alt="" height="100px" width="100%" />
            </a>
          </div>
          <div class="col-3">
            <a class="photo" href="#">
              <img 100px src="{% static 'images/b2.jpg' %}" alt="" height="100px"  width="100%" />
            </a>
          </div>
          <div class="col-3">
            <a class="photo" href="#">
              <img 100px src="{% static 'images/b3.jpeg' %}" alt="" height="100px" width="100%"  />
            </a>
          </div>
          <div class="col-3">
            <a class="photo" href="#">
              <img 100px src="{% static 'images/b4.jpeg' %}" alt="" height="100px" width="100%"  />
            </a>
          </div>
        </div>
      </div>
      <div class="col-sm-6">
        <div class="row no-gutters">
          <div class="col-3">
            <a class="photo" href="#">
              <img 100px src="{% static 'images/b5.jpeg' %}" alt=""height="100px" width="100%"  />
            </a>
          </div>
          <div class="col-3">
            <a class="photo" href="#">
              <img 100px src="{% static 'images/b6.jpeg' %}" alt="" height="100px" width="100%"  />
            </a>
          </div>
          <div class="col-3">
            <a class="photo" href="#">
              <img 100px src="{% static 'images/b7.jpeg' %}" alt="" height="100px" width="100%" />
            </a>
          </div>
          <div class="col-3">
            <a class="photo" href="#">
              <img 100px src="{% static 'images/b8.jpeg' %}" alt="" height="100px" width="100%" />
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

  <footer class="site-footer bg-darkest">
    <div class="container">

      <ul class="nav justify-content-center">
        <li class="nav-item">
          <a class="nav-link" href="#">Privacy policy</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Terms</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/contact">Feedback</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/advertise">Advertise</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/contact">Contact</a>
        </li>
      </ul>
      <div class="copy">
        &copy; Knowledge booster 2019<br />
        All rights reserved
      </div>
    </div>
  </footer>
                      

         

        {% block script %}
        {% endblock %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

booster/templates/pagination.html
<div class="pagination">
        <span class="step-links">
        {% if page.has_previous %}
        <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}
        <span class="current">
        Page {{ page.number }} of {{ page.paginator.num_pages }}.
        </span>
        {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
        </span>
       </div>